/* DESCRIPTION:
 * This code measures and reports the latencies of all functions 
 * relating to the red LED peripheral.
 */

#include "system.h"
#include "MPC.h"			// The library holding all MPC OS commands.
#include "INFO.h"			// Information about the whole multicore system (central system.h)
#include <sys/alt_irq.h>
#include "altera_avalon_timer_regs.h"
#include "altera_avalon_performance_counter.h"

alt_u8 COUNTER8			= 0;
alt_u32 COUNTER32		= 0;

alt_u32 INDEX 			= 0;
alt_u32 TIMER			= 0;
alt_u32 ITERATIONS		= 10000;

alt_u32 TIMER_MIN		= 1000000;
alt_u32 TIMER_MAX		= 0;

alt_u32 MEASURED_MIN	= 1000000;
alt_u32 MEASURED_MAX	= 0;

alt_u32 PERF_OVERHEAD	= 16;

int main()
{
	printf("\033c");
	printf("CORE %u\n",CPU_3);

	MPC_initialize_fifos(CPU_3, 12, 1);
	MPC_receive_from_CPU(CPU_2, CPU_3);

	printf("\n\n-------- WRITE SINGLE RED LED --------\n\n");

	printf("\nWrite Single Red LED - Immediate\n\n");

	alt_irq_context CONTEXT;
	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(0);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
	
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 0 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 0 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(1);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 1 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 1 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(2);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 2 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 2 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(3);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 3 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 3 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(4);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 4 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 4 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(5);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 5 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 5 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(6);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 6 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 6 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(7);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 7 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 7 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(8);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 8 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 8 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(9);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 9 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 9 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(10);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 10 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 10 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(11);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 11 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 11 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(12);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 12 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 12 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(13);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 13 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 13 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(14);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 14 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 14 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(15);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 15 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 15 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(16);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 16 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 16 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(17);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 17 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 17 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;


	printf("\nWRITE RED LED MIN: %u\n",MEASURED_MIN);
	printf("WRITE RED LED MAX: %u\n",MEASURED_MAX);

	MEASURED_MIN = 1000000;
	MEASURED_MAX = 0;




	printf("\nWrite Single Red LED - alt_u8\n\n");

for(COUNTER8 = 0; COUNTER8 < 18; COUNTER8++){
	CONTEXT = alt_irq_disable_all();
	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_single_red_LED(COUNTER8);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED %u MIN: %u\n",COUNTER8,TIMER_MIN);
	printf("WRITE RED LED %u MAX: %u\n",COUNTER8,TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;
}

	printf("\nWRITE RED LED MIN: %u\n",MEASURED_MIN);
	printf("WRITE RED LED MAX: %u\n",MEASURED_MAX);

	MEASURED_MIN = 1000000;
	MEASURED_MAX = 0;


//NEXT TEST



printf("\n\n-------- WRITE MASK RED LED --------\n\n");

	printf("\nWrite Mask Red LED - Immediate\n\n");

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_mask_red_LED(0x3FFFF);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
	
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("WRITE RED LED 0 MIN: %u\n",TIMER_MIN);
	printf("WRITE RED LED 0 MAX: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;


	printf("\nWrite Mask RED LED - alt_u32\n\n");


	CONTEXT = alt_irq_disable_all();
	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_write_mask_red_LED(COUNTER32);

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
		

	alt_irq_enable_all(CONTEXT);

	printf("WRITE MASK RED LED MIN	: %u\n",TIMER_MIN);
	printf("WRITE MASK RED LED MAX	: %u\n",TIMER_MAX);

	TIMER_MIN = 1000000;
	TIMER_MAX = 0;


//NEXT TEST



printf("\n\n-------- RESET RED LED --------\n\n");

	printf("\nReset Red LED - No Argument\n\n");

	CONTEXT = alt_irq_disable_all();

	for(INDEX = 0; INDEX < ITERATIONS; INDEX++){

		PERF_RESET(PERFORMANCE_COUNTER_3_BASE);

		PERF_START_MEASURING(PERFORMANCE_COUNTER_3_BASE);	
		PERF_BEGIN(PERFORMANCE_COUNTER_3_BASE,1);

		MPC_reset_red_leds();

		PERF_END(PERFORMANCE_COUNTER_3_BASE,1);	
		PERF_STOP_MEASURING(PERFORMANCE_COUNTER_3_BASE);

		TIMER = perf_get_section_time(PERFORMANCE_COUNTER_3_BASE, 1)-PERF_OVERHEAD;

		if(TIMER < TIMER_MIN){
			TIMER_MIN = TIMER;
		}
		if(TIMER > TIMER_MAX){
			TIMER_MAX = TIMER;
		}

	}
	
	if(TIMER_MIN < MEASURED_MIN){
		MEASURED_MIN = TIMER_MIN;
		}
	if(TIMER_MAX > MEASURED_MAX){
		MEASURED_MAX = TIMER_MAX;
		}

	alt_irq_enable_all(CONTEXT);

	printf("RESET RED LED 0 MIN: %u\n",TIMER_MIN);
	printf("RESET RED LED 0 MAX: %u\n",TIMER_MAX);

	return 0;
}
