/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu_6' in SOPC Builder design 'Core8'
 * SOPC Builder design path: ../../hardware/Core7.sopcinfo
 *
 * Generated: Wed Jun 23 17:07:56 UTC 2021
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x820
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 3
#define ALT_CPU_CPU_ID_VALUE 0x00000007
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x12
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x10020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x12
#define ALT_CPU_NAME "cpu_6"
#define ALT_CPU_RESET_ADDR 0x10000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x820
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 3
#define NIOS2_CPU_ID_VALUE 0x00000007
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x12
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x10020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x12
#define NIOS2_RESET_ADDR 0x10000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_MUTEX
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PERFORMANCE_COUNTER
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_QSYS


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_6"
#define ALT_STDERR_BASE 0x1320
#define ALT_STDERR_DEV jtag_uart_6
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_6"
#define ALT_STDIN_BASE 0x1320
#define ALT_STDIN_DEV jtag_uart_6
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_6"
#define ALT_STDOUT_BASE 0x1320
#define ALT_STDOUT_DEV jtag_uart_6
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "Core8"


/*
 * fifo_0_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_0_to_6_out altera_avalon_fifo
#define FIFO_0_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_0_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_0_TO_6_OUT_BASE 0x135c
#define FIFO_0_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_0_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_0_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_0_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_0_TO_6_OUT_IRQ -1
#define FIFO_0_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_0_TO_6_OUT_NAME "/dev/fifo_0_to_6_out"
#define FIFO_0_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_0_TO_6_OUT_SPAN 4
#define FIFO_0_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_0_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_0_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_0_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_0_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_0_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_0_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_0_TO_6_OUT_USE_IRQ 0
#define FIFO_0_TO_6_OUT_USE_PACKET 1
#define FIFO_0_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_0_TO_6_OUT_USE_REGISTER 0
#define FIFO_0_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_0_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_0_to_6_out_csr altera_avalon_fifo
#define FIFO_0_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_0_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_0_TO_6_OUT_CSR_BASE 0x1280
#define FIFO_0_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_0_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_0_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_0_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_0_TO_6_OUT_CSR_IRQ -1
#define FIFO_0_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_0_TO_6_OUT_CSR_NAME "/dev/fifo_0_to_6_out_csr"
#define FIFO_0_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_0_TO_6_OUT_CSR_SPAN 32
#define FIFO_0_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_0_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_0_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_0_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_0_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_0_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_0_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_0_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_0_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_0_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_0_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_0_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1_to_6_out altera_avalon_fifo
#define FIFO_1_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1_TO_6_OUT_BASE 0x1358
#define FIFO_1_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_1_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_1_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_1_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_1_TO_6_OUT_IRQ -1
#define FIFO_1_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1_TO_6_OUT_NAME "/dev/fifo_1_to_6_out"
#define FIFO_1_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_1_TO_6_OUT_SPAN 4
#define FIFO_1_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_1_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_1_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_1_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_1_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_1_TO_6_OUT_USE_IRQ 0
#define FIFO_1_TO_6_OUT_USE_PACKET 1
#define FIFO_1_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_1_TO_6_OUT_USE_REGISTER 0
#define FIFO_1_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_1_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1_to_6_out_csr altera_avalon_fifo
#define FIFO_1_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1_TO_6_OUT_CSR_BASE 0x1260
#define FIFO_1_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_1_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_1_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_1_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_1_TO_6_OUT_CSR_IRQ -1
#define FIFO_1_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1_TO_6_OUT_CSR_NAME "/dev/fifo_1_to_6_out_csr"
#define FIFO_1_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1_TO_6_OUT_CSR_SPAN 32
#define FIFO_1_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_1_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_1_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_1_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_1_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_1_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_1_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_1_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_2_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_2_to_6_out altera_avalon_fifo
#define FIFO_2_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_2_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_2_TO_6_OUT_BASE 0x1354
#define FIFO_2_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_2_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_2_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_2_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_2_TO_6_OUT_IRQ -1
#define FIFO_2_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_2_TO_6_OUT_NAME "/dev/fifo_2_to_6_out"
#define FIFO_2_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_2_TO_6_OUT_SPAN 4
#define FIFO_2_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_2_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_2_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_2_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_2_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_2_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_2_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_2_TO_6_OUT_USE_IRQ 0
#define FIFO_2_TO_6_OUT_USE_PACKET 1
#define FIFO_2_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_2_TO_6_OUT_USE_REGISTER 0
#define FIFO_2_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_2_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_2_to_6_out_csr altera_avalon_fifo
#define FIFO_2_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_2_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_2_TO_6_OUT_CSR_BASE 0x1240
#define FIFO_2_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_2_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_2_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_2_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_2_TO_6_OUT_CSR_IRQ -1
#define FIFO_2_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_2_TO_6_OUT_CSR_NAME "/dev/fifo_2_to_6_out_csr"
#define FIFO_2_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_2_TO_6_OUT_CSR_SPAN 32
#define FIFO_2_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_2_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_2_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_2_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_2_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_2_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_2_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_2_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_2_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_2_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_2_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_2_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_3_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_3_to_6_out altera_avalon_fifo
#define FIFO_3_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_3_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_3_TO_6_OUT_BASE 0x1350
#define FIFO_3_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_3_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_3_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_3_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_3_TO_6_OUT_IRQ -1
#define FIFO_3_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_3_TO_6_OUT_NAME "/dev/fifo_3_to_6_out"
#define FIFO_3_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_3_TO_6_OUT_SPAN 4
#define FIFO_3_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_3_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_3_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_3_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_3_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_3_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_3_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_3_TO_6_OUT_USE_IRQ 0
#define FIFO_3_TO_6_OUT_USE_PACKET 1
#define FIFO_3_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_3_TO_6_OUT_USE_REGISTER 0
#define FIFO_3_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_3_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_3_to_6_out_csr altera_avalon_fifo
#define FIFO_3_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_3_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_3_TO_6_OUT_CSR_BASE 0x1220
#define FIFO_3_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_3_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_3_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_3_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_3_TO_6_OUT_CSR_IRQ -1
#define FIFO_3_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_3_TO_6_OUT_CSR_NAME "/dev/fifo_3_to_6_out_csr"
#define FIFO_3_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_3_TO_6_OUT_CSR_SPAN 32
#define FIFO_3_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_3_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_3_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_3_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_3_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_3_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_3_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_3_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_3_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_3_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_3_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_3_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_4_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_4_to_6_out altera_avalon_fifo
#define FIFO_4_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_4_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_4_TO_6_OUT_BASE 0x134c
#define FIFO_4_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_4_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_4_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_4_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_4_TO_6_OUT_IRQ -1
#define FIFO_4_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_4_TO_6_OUT_NAME "/dev/fifo_4_to_6_out"
#define FIFO_4_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_4_TO_6_OUT_SPAN 4
#define FIFO_4_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_4_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_4_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_4_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_4_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_4_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_4_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_4_TO_6_OUT_USE_IRQ 0
#define FIFO_4_TO_6_OUT_USE_PACKET 1
#define FIFO_4_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_4_TO_6_OUT_USE_REGISTER 0
#define FIFO_4_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_4_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_4_to_6_out_csr altera_avalon_fifo
#define FIFO_4_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_4_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_4_TO_6_OUT_CSR_BASE 0x1200
#define FIFO_4_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_4_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_4_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_4_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_4_TO_6_OUT_CSR_IRQ -1
#define FIFO_4_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_4_TO_6_OUT_CSR_NAME "/dev/fifo_4_to_6_out_csr"
#define FIFO_4_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_4_TO_6_OUT_CSR_SPAN 32
#define FIFO_4_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_4_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_4_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_4_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_4_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_4_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_4_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_4_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_4_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_4_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_4_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_4_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_5_to_6_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_5_to_6_out altera_avalon_fifo
#define FIFO_5_TO_6_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_5_TO_6_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_5_TO_6_OUT_BASE 0x1348
#define FIFO_5_TO_6_OUT_BITS_PER_SYMBOL 16
#define FIFO_5_TO_6_OUT_CHANNEL_WIDTH 8
#define FIFO_5_TO_6_OUT_ERROR_WIDTH 8
#define FIFO_5_TO_6_OUT_FIFO_DEPTH 16
#define FIFO_5_TO_6_OUT_IRQ -1
#define FIFO_5_TO_6_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_5_TO_6_OUT_NAME "/dev/fifo_5_to_6_out"
#define FIFO_5_TO_6_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_5_TO_6_OUT_SPAN 4
#define FIFO_5_TO_6_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_5_TO_6_OUT_TYPE "altera_avalon_fifo"
#define FIFO_5_TO_6_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_5_TO_6_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_5_TO_6_OUT_USE_AVALONST_SINK 0
#define FIFO_5_TO_6_OUT_USE_AVALONST_SOURCE 0
#define FIFO_5_TO_6_OUT_USE_BACKPRESSURE 1
#define FIFO_5_TO_6_OUT_USE_IRQ 0
#define FIFO_5_TO_6_OUT_USE_PACKET 1
#define FIFO_5_TO_6_OUT_USE_READ_CONTROL 1
#define FIFO_5_TO_6_OUT_USE_REGISTER 0
#define FIFO_5_TO_6_OUT_USE_WRITE_CONTROL 1


/*
 * fifo_5_to_6_out_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_5_to_6_out_csr altera_avalon_fifo
#define FIFO_5_TO_6_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_5_TO_6_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_5_TO_6_OUT_CSR_BASE 0x11e0
#define FIFO_5_TO_6_OUT_CSR_BITS_PER_SYMBOL 16
#define FIFO_5_TO_6_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_5_TO_6_OUT_CSR_ERROR_WIDTH 8
#define FIFO_5_TO_6_OUT_CSR_FIFO_DEPTH 16
#define FIFO_5_TO_6_OUT_CSR_IRQ -1
#define FIFO_5_TO_6_OUT_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_5_TO_6_OUT_CSR_NAME "/dev/fifo_5_to_6_out_csr"
#define FIFO_5_TO_6_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_5_TO_6_OUT_CSR_SPAN 32
#define FIFO_5_TO_6_OUT_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_5_TO_6_OUT_CSR_TYPE "altera_avalon_fifo"
#define FIFO_5_TO_6_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_5_TO_6_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_5_TO_6_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_5_TO_6_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_5_TO_6_OUT_CSR_USE_BACKPRESSURE 1
#define FIFO_5_TO_6_OUT_CSR_USE_IRQ 0
#define FIFO_5_TO_6_OUT_CSR_USE_PACKET 1
#define FIFO_5_TO_6_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_5_TO_6_OUT_CSR_USE_REGISTER 0
#define FIFO_5_TO_6_OUT_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_0_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_0_in altera_avalon_fifo
#define FIFO_6_TO_0_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_0_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_0_IN_BASE 0x1344
#define FIFO_6_TO_0_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_0_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_0_IN_ERROR_WIDTH 8
#define FIFO_6_TO_0_IN_FIFO_DEPTH 16
#define FIFO_6_TO_0_IN_IRQ -1
#define FIFO_6_TO_0_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_0_IN_NAME "/dev/fifo_6_to_0_in"
#define FIFO_6_TO_0_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_0_IN_SPAN 4
#define FIFO_6_TO_0_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_0_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_0_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_0_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_0_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_0_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_0_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_0_IN_USE_IRQ 0
#define FIFO_6_TO_0_IN_USE_PACKET 1
#define FIFO_6_TO_0_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_0_IN_USE_REGISTER 0
#define FIFO_6_TO_0_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_0_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_0_in_csr altera_avalon_fifo
#define FIFO_6_TO_0_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_0_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_0_IN_CSR_BASE 0x11a0
#define FIFO_6_TO_0_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_0_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_0_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_0_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_0_IN_CSR_IRQ -1
#define FIFO_6_TO_0_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_0_IN_CSR_NAME "/dev/fifo_6_to_0_in_csr"
#define FIFO_6_TO_0_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_0_IN_CSR_SPAN 32
#define FIFO_6_TO_0_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_0_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_0_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_0_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_0_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_0_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_0_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_0_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_0_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_0_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_0_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_0_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_1_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_1_in altera_avalon_fifo
#define FIFO_6_TO_1_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_1_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_1_IN_BASE 0x1340
#define FIFO_6_TO_1_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_1_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_1_IN_ERROR_WIDTH 8
#define FIFO_6_TO_1_IN_FIFO_DEPTH 16
#define FIFO_6_TO_1_IN_IRQ -1
#define FIFO_6_TO_1_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_1_IN_NAME "/dev/fifo_6_to_1_in"
#define FIFO_6_TO_1_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_1_IN_SPAN 4
#define FIFO_6_TO_1_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_1_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_1_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_1_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_1_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_1_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_1_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_1_IN_USE_IRQ 0
#define FIFO_6_TO_1_IN_USE_PACKET 1
#define FIFO_6_TO_1_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_1_IN_USE_REGISTER 0
#define FIFO_6_TO_1_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_1_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_1_in_csr altera_avalon_fifo
#define FIFO_6_TO_1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_1_IN_CSR_BASE 0x1180
#define FIFO_6_TO_1_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_1_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_1_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_1_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_1_IN_CSR_IRQ -1
#define FIFO_6_TO_1_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_1_IN_CSR_NAME "/dev/fifo_6_to_1_in_csr"
#define FIFO_6_TO_1_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_1_IN_CSR_SPAN 32
#define FIFO_6_TO_1_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_1_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_1_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_1_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_1_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_1_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_1_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_1_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_1_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_2_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_2_in altera_avalon_fifo
#define FIFO_6_TO_2_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_2_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_2_IN_BASE 0x133c
#define FIFO_6_TO_2_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_2_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_2_IN_ERROR_WIDTH 8
#define FIFO_6_TO_2_IN_FIFO_DEPTH 16
#define FIFO_6_TO_2_IN_IRQ -1
#define FIFO_6_TO_2_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_2_IN_NAME "/dev/fifo_6_to_2_in"
#define FIFO_6_TO_2_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_2_IN_SPAN 4
#define FIFO_6_TO_2_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_2_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_2_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_2_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_2_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_2_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_2_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_2_IN_USE_IRQ 0
#define FIFO_6_TO_2_IN_USE_PACKET 1
#define FIFO_6_TO_2_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_2_IN_USE_REGISTER 0
#define FIFO_6_TO_2_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_2_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_2_in_csr altera_avalon_fifo
#define FIFO_6_TO_2_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_2_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_2_IN_CSR_BASE 0x1160
#define FIFO_6_TO_2_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_2_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_2_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_2_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_2_IN_CSR_IRQ -1
#define FIFO_6_TO_2_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_2_IN_CSR_NAME "/dev/fifo_6_to_2_in_csr"
#define FIFO_6_TO_2_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_2_IN_CSR_SPAN 32
#define FIFO_6_TO_2_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_2_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_2_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_2_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_2_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_2_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_2_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_2_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_2_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_2_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_2_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_2_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_3_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_3_in altera_avalon_fifo
#define FIFO_6_TO_3_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_3_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_3_IN_BASE 0x1338
#define FIFO_6_TO_3_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_3_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_3_IN_ERROR_WIDTH 8
#define FIFO_6_TO_3_IN_FIFO_DEPTH 16
#define FIFO_6_TO_3_IN_IRQ -1
#define FIFO_6_TO_3_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_3_IN_NAME "/dev/fifo_6_to_3_in"
#define FIFO_6_TO_3_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_3_IN_SPAN 4
#define FIFO_6_TO_3_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_3_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_3_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_3_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_3_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_3_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_3_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_3_IN_USE_IRQ 0
#define FIFO_6_TO_3_IN_USE_PACKET 1
#define FIFO_6_TO_3_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_3_IN_USE_REGISTER 0
#define FIFO_6_TO_3_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_3_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_3_in_csr altera_avalon_fifo
#define FIFO_6_TO_3_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_3_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_3_IN_CSR_BASE 0x1140
#define FIFO_6_TO_3_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_3_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_3_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_3_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_3_IN_CSR_IRQ -1
#define FIFO_6_TO_3_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_3_IN_CSR_NAME "/dev/fifo_6_to_3_in_csr"
#define FIFO_6_TO_3_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_3_IN_CSR_SPAN 32
#define FIFO_6_TO_3_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_3_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_3_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_3_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_3_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_3_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_3_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_3_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_3_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_3_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_3_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_3_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_4_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_4_in altera_avalon_fifo
#define FIFO_6_TO_4_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_4_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_4_IN_BASE 0x1334
#define FIFO_6_TO_4_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_4_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_4_IN_ERROR_WIDTH 8
#define FIFO_6_TO_4_IN_FIFO_DEPTH 16
#define FIFO_6_TO_4_IN_IRQ -1
#define FIFO_6_TO_4_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_4_IN_NAME "/dev/fifo_6_to_4_in"
#define FIFO_6_TO_4_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_4_IN_SPAN 4
#define FIFO_6_TO_4_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_4_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_4_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_4_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_4_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_4_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_4_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_4_IN_USE_IRQ 0
#define FIFO_6_TO_4_IN_USE_PACKET 1
#define FIFO_6_TO_4_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_4_IN_USE_REGISTER 0
#define FIFO_6_TO_4_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_4_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_4_in_csr altera_avalon_fifo
#define FIFO_6_TO_4_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_4_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_4_IN_CSR_BASE 0x1120
#define FIFO_6_TO_4_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_4_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_4_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_4_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_4_IN_CSR_IRQ -1
#define FIFO_6_TO_4_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_4_IN_CSR_NAME "/dev/fifo_6_to_4_in_csr"
#define FIFO_6_TO_4_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_4_IN_CSR_SPAN 32
#define FIFO_6_TO_4_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_4_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_4_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_4_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_4_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_4_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_4_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_4_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_4_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_4_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_4_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_4_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_5_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_5_in altera_avalon_fifo
#define FIFO_6_TO_5_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_5_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_5_IN_BASE 0x1330
#define FIFO_6_TO_5_IN_BITS_PER_SYMBOL 16
#define FIFO_6_TO_5_IN_CHANNEL_WIDTH 8
#define FIFO_6_TO_5_IN_ERROR_WIDTH 8
#define FIFO_6_TO_5_IN_FIFO_DEPTH 16
#define FIFO_6_TO_5_IN_IRQ -1
#define FIFO_6_TO_5_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_5_IN_NAME "/dev/fifo_6_to_5_in"
#define FIFO_6_TO_5_IN_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_5_IN_SPAN 4
#define FIFO_6_TO_5_IN_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_5_IN_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_5_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_5_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_5_IN_USE_AVALONST_SINK 0
#define FIFO_6_TO_5_IN_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_5_IN_USE_BACKPRESSURE 1
#define FIFO_6_TO_5_IN_USE_IRQ 0
#define FIFO_6_TO_5_IN_USE_PACKET 1
#define FIFO_6_TO_5_IN_USE_READ_CONTROL 1
#define FIFO_6_TO_5_IN_USE_REGISTER 0
#define FIFO_6_TO_5_IN_USE_WRITE_CONTROL 1


/*
 * fifo_6_to_5_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_6_to_5_in_csr altera_avalon_fifo
#define FIFO_6_TO_5_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_6_TO_5_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_6_TO_5_IN_CSR_BASE 0x1100
#define FIFO_6_TO_5_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_6_TO_5_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_6_TO_5_IN_CSR_ERROR_WIDTH 8
#define FIFO_6_TO_5_IN_CSR_FIFO_DEPTH 16
#define FIFO_6_TO_5_IN_CSR_IRQ -1
#define FIFO_6_TO_5_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_6_TO_5_IN_CSR_NAME "/dev/fifo_6_to_5_in_csr"
#define FIFO_6_TO_5_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_6_TO_5_IN_CSR_SPAN 32
#define FIFO_6_TO_5_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_6_TO_5_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_6_TO_5_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_6_TO_5_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_6_TO_5_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_6_TO_5_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_6_TO_5_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_6_TO_5_IN_CSR_USE_IRQ 0
#define FIFO_6_TO_5_IN_CSR_USE_PACKET 1
#define FIFO_6_TO_5_IN_CSR_USE_READ_CONTROL 1
#define FIFO_6_TO_5_IN_CSR_USE_REGISTER 0
#define FIFO_6_TO_5_IN_CSR_USE_WRITE_CONTROL 1


/*
 * green_leds configuration
 *
 */

#define ALT_MODULE_CLASS_green_leds altera_avalon_pio
#define GREEN_LEDS_BASE 0x12d0
#define GREEN_LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define GREEN_LEDS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GREEN_LEDS_CAPTURE 0
#define GREEN_LEDS_DATA_WIDTH 8
#define GREEN_LEDS_DO_TEST_BENCH_WIRING 0
#define GREEN_LEDS_DRIVEN_SIM_VALUE 0
#define GREEN_LEDS_EDGE_TYPE "NONE"
#define GREEN_LEDS_FREQ 50000000
#define GREEN_LEDS_HAS_IN 0
#define GREEN_LEDS_HAS_OUT 1
#define GREEN_LEDS_HAS_TRI 0
#define GREEN_LEDS_IRQ -1
#define GREEN_LEDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GREEN_LEDS_IRQ_TYPE "NONE"
#define GREEN_LEDS_NAME "/dev/green_leds"
#define GREEN_LEDS_RESET_VALUE 0
#define GREEN_LEDS_SPAN 16
#define GREEN_LEDS_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 4
#define ALT_SYS_CLK TIMER_6_0
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_6 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_6 altera_avalon_jtag_uart
#define JTAG_UART_6_BASE 0x1320
#define JTAG_UART_6_IRQ 16
#define JTAG_UART_6_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_6_NAME "/dev/jtag_uart_6"
#define JTAG_UART_6_READ_DEPTH 64
#define JTAG_UART_6_READ_THRESHOLD 8
#define JTAG_UART_6_SPAN 8
#define JTAG_UART_6_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_6_WRITE_DEPTH 64
#define JTAG_UART_6_WRITE_THRESHOLD 8


/*
 * mutex_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_0 altera_avalon_mutex
#define MUTEX_0_BASE 0x1318
#define MUTEX_0_IRQ -1
#define MUTEX_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_0_NAME "/dev/mutex_0"
#define MUTEX_0_OWNER_INIT 0
#define MUTEX_0_OWNER_WIDTH 16
#define MUTEX_0_SPAN 8
#define MUTEX_0_TYPE "altera_avalon_mutex"
#define MUTEX_0_VALUE_INIT 0
#define MUTEX_0_VALUE_WIDTH 16


/*
 * mutex_1 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_1 altera_avalon_mutex
#define MUTEX_1_BASE 0x1310
#define MUTEX_1_IRQ -1
#define MUTEX_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_1_NAME "/dev/mutex_1"
#define MUTEX_1_OWNER_INIT 0
#define MUTEX_1_OWNER_WIDTH 16
#define MUTEX_1_SPAN 8
#define MUTEX_1_TYPE "altera_avalon_mutex"
#define MUTEX_1_VALUE_INIT 0
#define MUTEX_1_VALUE_WIDTH 16


/*
 * mutex_2 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_2 altera_avalon_mutex
#define MUTEX_2_BASE 0x1308
#define MUTEX_2_IRQ -1
#define MUTEX_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_2_NAME "/dev/mutex_2"
#define MUTEX_2_OWNER_INIT 0
#define MUTEX_2_OWNER_WIDTH 16
#define MUTEX_2_SPAN 8
#define MUTEX_2_TYPE "altera_avalon_mutex"
#define MUTEX_2_VALUE_INIT 0
#define MUTEX_2_VALUE_WIDTH 16


/*
 * mutex_3 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_3 altera_avalon_mutex
#define MUTEX_3_BASE 0x1300
#define MUTEX_3_IRQ -1
#define MUTEX_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_3_NAME "/dev/mutex_3"
#define MUTEX_3_OWNER_INIT 0
#define MUTEX_3_OWNER_WIDTH 16
#define MUTEX_3_SPAN 8
#define MUTEX_3_TYPE "altera_avalon_mutex"
#define MUTEX_3_VALUE_INIT 0
#define MUTEX_3_VALUE_WIDTH 16


/*
 * mutex_4 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_4 altera_avalon_mutex
#define MUTEX_4_BASE 0x12f8
#define MUTEX_4_IRQ -1
#define MUTEX_4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_4_NAME "/dev/mutex_4"
#define MUTEX_4_OWNER_INIT 0
#define MUTEX_4_OWNER_WIDTH 16
#define MUTEX_4_SPAN 8
#define MUTEX_4_TYPE "altera_avalon_mutex"
#define MUTEX_4_VALUE_INIT 0
#define MUTEX_4_VALUE_WIDTH 16


/*
 * mutex_5 configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_5 altera_avalon_mutex
#define MUTEX_5_BASE 0x12f0
#define MUTEX_5_IRQ -1
#define MUTEX_5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_5_NAME "/dev/mutex_5"
#define MUTEX_5_OWNER_INIT 0
#define MUTEX_5_OWNER_WIDTH 16
#define MUTEX_5_SPAN 8
#define MUTEX_5_TYPE "altera_avalon_mutex"
#define MUTEX_5_VALUE_INIT 0
#define MUTEX_5_VALUE_WIDTH 16


/*
 * onchip_memory_6 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory_6 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_6_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_6_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_6_BASE 0x10000
#define ONCHIP_MEMORY_6_CONTENTS_INFO ""
#define ONCHIP_MEMORY_6_DUAL_PORT 0
#define ONCHIP_MEMORY_6_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_6_INIT_CONTENTS_FILE "Core8_onchip_memory_6"
#define ONCHIP_MEMORY_6_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_6_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_6_IRQ -1
#define ONCHIP_MEMORY_6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_6_NAME "/dev/onchip_memory_6"
#define ONCHIP_MEMORY_6_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_6_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_6_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_6_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_6_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_6_SIZE_VALUE 32768
#define ONCHIP_MEMORY_6_SPAN 32768
#define ONCHIP_MEMORY_6_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_6_WRITABLE 1


/*
 * onchip_shared configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_shared altera_avalon_onchip_memory2
#define ONCHIP_SHARED_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_SHARED_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_SHARED_BASE 0x20000
#define ONCHIP_SHARED_CONTENTS_INFO ""
#define ONCHIP_SHARED_DUAL_PORT 0
#define ONCHIP_SHARED_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_SHARED_INIT_CONTENTS_FILE "Core8_onchip_shared"
#define ONCHIP_SHARED_INIT_MEM_CONTENT 1
#define ONCHIP_SHARED_INSTANCE_ID "NONE"
#define ONCHIP_SHARED_IRQ -1
#define ONCHIP_SHARED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_SHARED_NAME "/dev/onchip_shared"
#define ONCHIP_SHARED_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_SHARED_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_SHARED_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_SHARED_SINGLE_CLOCK_OP 0
#define ONCHIP_SHARED_SIZE_MULTIPLE 1
#define ONCHIP_SHARED_SIZE_VALUE 65536
#define ONCHIP_SHARED_SPAN 65536
#define ONCHIP_SHARED_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_SHARED_WRITABLE 1


/*
 * performance_counter_6 configuration
 *
 */

#define ALT_MODULE_CLASS_performance_counter_6 altera_avalon_performance_counter
#define PERFORMANCE_COUNTER_6_BASE 0x1000
#define PERFORMANCE_COUNTER_6_HOW_MANY_SECTIONS 7
#define PERFORMANCE_COUNTER_6_IRQ -1
#define PERFORMANCE_COUNTER_6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERFORMANCE_COUNTER_6_NAME "/dev/performance_counter_6"
#define PERFORMANCE_COUNTER_6_SPAN 128
#define PERFORMANCE_COUNTER_6_TYPE "altera_avalon_performance_counter"


/*
 * red_leds configuration
 *
 */

#define ALT_MODULE_CLASS_red_leds altera_avalon_pio
#define RED_LEDS_BASE 0x12e0
#define RED_LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define RED_LEDS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RED_LEDS_CAPTURE 0
#define RED_LEDS_DATA_WIDTH 18
#define RED_LEDS_DO_TEST_BENCH_WIRING 0
#define RED_LEDS_DRIVEN_SIM_VALUE 0
#define RED_LEDS_EDGE_TYPE "NONE"
#define RED_LEDS_FREQ 50000000
#define RED_LEDS_HAS_IN 0
#define RED_LEDS_HAS_OUT 1
#define RED_LEDS_HAS_TRI 0
#define RED_LEDS_IRQ -1
#define RED_LEDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RED_LEDS_IRQ_TYPE "NONE"
#define RED_LEDS_NAME "/dev/red_leds"
#define RED_LEDS_RESET_VALUE 0
#define RED_LEDS_SPAN 16
#define RED_LEDS_TYPE "altera_avalon_pio"


/*
 * switches configuration
 *
 */

#define ALT_MODULE_CLASS_switches altera_avalon_pio
#define SWITCHES_BASE 0x12c0
#define SWITCHES_BIT_CLEARING_EDGE_REGISTER 0
#define SWITCHES_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SWITCHES_CAPTURE 0
#define SWITCHES_DATA_WIDTH 18
#define SWITCHES_DO_TEST_BENCH_WIRING 0
#define SWITCHES_DRIVEN_SIM_VALUE 0
#define SWITCHES_EDGE_TYPE "NONE"
#define SWITCHES_FREQ 50000000
#define SWITCHES_HAS_IN 1
#define SWITCHES_HAS_OUT 0
#define SWITCHES_HAS_TRI 0
#define SWITCHES_IRQ -1
#define SWITCHES_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SWITCHES_IRQ_TYPE "NONE"
#define SWITCHES_NAME "/dev/switches"
#define SWITCHES_RESET_VALUE 0
#define SWITCHES_SPAN 16
#define SWITCHES_TYPE "altera_avalon_pio"


/*
 * timer_6_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_6_0 altera_avalon_timer
#define TIMER_6_0_ALWAYS_RUN 0
#define TIMER_6_0_BASE 0x12a0
#define TIMER_6_0_COUNTER_SIZE 32
#define TIMER_6_0_FIXED_PERIOD 0
#define TIMER_6_0_FREQ 50000000
#define TIMER_6_0_IRQ 0
#define TIMER_6_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_6_0_LOAD_VALUE 49999
#define TIMER_6_0_MULT 0.0010
#define TIMER_6_0_NAME "/dev/timer_6_0"
#define TIMER_6_0_PERIOD 1
#define TIMER_6_0_PERIOD_UNITS "ms"
#define TIMER_6_0_RESET_OUTPUT 0
#define TIMER_6_0_SNAPSHOT 1
#define TIMER_6_0_SPAN 32
#define TIMER_6_0_TICKS_PER_SEC 1000.0
#define TIMER_6_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_6_0_TYPE "altera_avalon_timer"


/*
 * timer_6_1 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_6_1 altera_avalon_timer
#define TIMER_6_1_ALWAYS_RUN 0
#define TIMER_6_1_BASE 0x10a0
#define TIMER_6_1_COUNTER_SIZE 32
#define TIMER_6_1_FIXED_PERIOD 0
#define TIMER_6_1_FREQ 50000000
#define TIMER_6_1_IRQ 1
#define TIMER_6_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_6_1_LOAD_VALUE 49999
#define TIMER_6_1_MULT 0.0010
#define TIMER_6_1_NAME "/dev/timer_6_1"
#define TIMER_6_1_PERIOD 1
#define TIMER_6_1_PERIOD_UNITS "ms"
#define TIMER_6_1_RESET_OUTPUT 0
#define TIMER_6_1_SNAPSHOT 1
#define TIMER_6_1_SPAN 32
#define TIMER_6_1_TICKS_PER_SEC 1000.0
#define TIMER_6_1_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_6_1_TYPE "altera_avalon_timer"


/*
 * timer_shared_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_shared_0 altera_avalon_timer
#define TIMER_SHARED_0_ALWAYS_RUN 0
#define TIMER_SHARED_0_BASE 0x11c0
#define TIMER_SHARED_0_COUNTER_SIZE 32
#define TIMER_SHARED_0_FIXED_PERIOD 0
#define TIMER_SHARED_0_FREQ 50000000
#define TIMER_SHARED_0_IRQ 2
#define TIMER_SHARED_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_SHARED_0_LOAD_VALUE 49999
#define TIMER_SHARED_0_MULT 0.0010
#define TIMER_SHARED_0_NAME "/dev/timer_shared_0"
#define TIMER_SHARED_0_PERIOD 1
#define TIMER_SHARED_0_PERIOD_UNITS "ms"
#define TIMER_SHARED_0_RESET_OUTPUT 0
#define TIMER_SHARED_0_SNAPSHOT 1
#define TIMER_SHARED_0_SPAN 32
#define TIMER_SHARED_0_TICKS_PER_SEC 1000.0
#define TIMER_SHARED_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_SHARED_0_TYPE "altera_avalon_timer"


/*
 * timer_shared_1 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_shared_1 altera_avalon_timer
#define TIMER_SHARED_1_ALWAYS_RUN 0
#define TIMER_SHARED_1_BASE 0x1080
#define TIMER_SHARED_1_COUNTER_SIZE 32
#define TIMER_SHARED_1_FIXED_PERIOD 0
#define TIMER_SHARED_1_FREQ 50000000
#define TIMER_SHARED_1_IRQ 3
#define TIMER_SHARED_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_SHARED_1_LOAD_VALUE 49999
#define TIMER_SHARED_1_MULT 0.0010
#define TIMER_SHARED_1_NAME "/dev/timer_shared_1"
#define TIMER_SHARED_1_PERIOD 1
#define TIMER_SHARED_1_PERIOD_UNITS "ms"
#define TIMER_SHARED_1_RESET_OUTPUT 0
#define TIMER_SHARED_1_SNAPSHOT 1
#define TIMER_SHARED_1_SPAN 32
#define TIMER_SHARED_1_TICKS_PER_SEC 1000.0
#define TIMER_SHARED_1_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_SHARED_1_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
